### ISSUE TITLE
Helm Chart

### ISSUE THREAD

**Issue by iterion** [getsentry/sentry-kubernetes#1]
Thanks for creating this project!

It would be helpful to have a helm chart to make this easy to install. I've created a first pass at one in the kubernetes/charts repo as an incubator project: https://github.com/kubernetes/charts/pull/2708

Just creating this issue for your visibility.

**Comment by bretthoerner** [comment]
Good idea, thanks!

**Comment by bretthoerner** [comment]
I subscribed to the other ticket.
