### ISSUE TITLE
Add ProtocolError exception handling to kubernetes.watch

### ISSUE THREAD

**Issue by kfyhn** [getsentry/sentry-kubernetes#11]
There is a known issue with handling ProtocolError using the Kubernetes Python SDK (see https://github.com/kubernetes-client/python/issues/540, https://github.com/datawire/ambassador/issues/554 and https://github.com/datawire/ambassador/pull/724). I am seeing this issue also when using the Docker image for sentry-kubernetes in k8 1.10.6. Please add similar handling to sentry-kubernetes and push a new Docker image.

**Comment by bretthoerner** [comment]
I probably won't be able to get to this in the short term, any chance you could create a PR?

**Comment by jonathanbeber** [comment]
It should be closed, right? 

see #12
