### ISSUE TITLE
Support for replicas

### ISSUE THREAD

**Issue by cpnielsen** [getsentry/sentry-kubernetes#14]
From what I can tell, running multiple instances of this docker images in kubernetes will result in duplicate events (since each pod reads their own stream of events).

Is there a way to have the two pods sync with each other or have Sentry skip identical events (if there is a way to determine such a thing). I am asking since in case of pod evictions or outages, this pod is a potential "victim" and if it gets evicted all events happening during that period will be lost. Having multiple pods (with anti-affinity to schedule them on different nodes) should help remedy that issue.

If you have an "official" way of solving this I am all ears.

**Comment by bretthoerner** [comment]
Hmm, I'm not sure how to have the two containers coordinate. I wonder if there's a simpler or more broadly used Kubernetes solution that can run two containers and have them share a lock in etcd or something? Like something at a higher level than this container itself.

But yeah, having it miss 0 events will present a real challenge. I guess we'd need some sort of way to look at old events and maintain (and store) a cursor?

**Comment by cpnielsen** [comment]
Yeah, I am aware that it is a tricky proposition. I was hoping that maybe Sentry has a notion of a "unique" event, so that it can filter out duplicates, but barring that we will need some coordination mechanism in Kubernetes. I will see if I can find a good approach 🤔

**Comment by bretthoerner** [comment]
We do dedupe by `(project_id, event_id)` pair on the Sentry side, so I guess if we generated the event_id by hasing the content (or the Kubernetes ID or something) we may be able to do this. I think that double sending may count against your event quota though, since we still partially process it. If that's acceptable (your Kube events are low enough) that may be a workable solution?

**Comment by jaitaiwan** [comment]
If you wanted to get a little complicated you could use a StatefulSet with a persistent volume. Log all kubernetes events to some sort of message queue and then send events off from there. If the stateful set crashes you still have the persistent volume storing the queue.

**Comment by cpnielsen** [comment]
Since I am no longer involved in projects where this is an issue, I am closing this. We did not find a "recommended" solution to this, so the underlying issue is still unsolved, to some extent.
