### ISSUE TITLE
add log_level via environment variable

### ISSUE THREAD

**Issue by joaocc** [getsentry/sentry-kubernetes#20]
Add support for providing log_level via environment variable in addition to `--log-level`.
When using the image in the kubernetes helm chart, there is no easy way to do this.
If the docker image recognizes LOG_LEVEL, then it's much easier to propose a PR to set that via heml chart values.

**Comment by bretthoerner** [comment]
https://github.com/getsentry/sentry-kubernetes/commit/108ae63cc7f0343bdb84fe7e9ff62e0d540dc0cb

**Comment by joaocc** [comment]
Many thanks!
