### ISSUE TITLE
No events being sent. What is the format expected by "DSN"?

### ISSUE THREAD

**Issue by joaocc** [getsentry/sentry-kubernetes#21]
We have installed sentry in 3 kubernetes clusters, using 
```
helm install \
    incubator/sentry-kubernetes \
    --name sentry\
    --namespace sys \
    --set rbac.create=false \
    --set sentry.dsn="https://ppppppub-keyyyyyyy@sentry.io/000000
```
None of the projects is receiving any data.
Container produces no log to stdout.

Any ideas on how to troubleshoot the setup?
Also, can anyone confirm the DNS format is correct or if it needs to be one of the alternatives ?
* https://pub-key@sentry.io/proj-id
* https://pub-key:priv-key@sentry.io/proj-id
* something else
Thx

**Comment by joaocc** [comment]
Everything seems to be working fine... Would be nice to have some of output on sentry pod on start and/on or initial connection to sentry.

**Comment by mislavcimpersak** [comment]
@joaocc so which DSN format was the correct one?
