### ISSUE TITLE
Add a manifest that can be used without helm

### ISSUE THREAD

**Issue by nesl247** [getsentry/sentry-kubernetes#26]
It would be great if you would provide a manifest file that can be used without helm.

Basically like: https://github.com/infracloudio/botkube/blob/master/deploy-all-in-one.yaml

**Comment by Bessonov** [comment]
The deployment file can be generated by `helm template` locally or on CI.

**Comment by nesl247** [comment]
We’ve actually since adopted helm. At the time though helm template wasn’t a great option for us.
