### ISSUE TITLE
Tag Docker Released Images with Version

### ISSUE THREAD

**Issue by BrianChristie** [getsentry/sentry-kubernetes#27]
The docker image has no version tags which means the deployed version cannot be pinned.
https://hub.docker.com/r/getsentry/sentry-kubernetes/tags

Please provide tagged releases on Docker Hub.

**Comment by maestrofjp** [comment]
@HazAT could we get a push to docker hub of the latest two PRs #25 and #24 ?

**Comment by tonyo** [comment]
Hey,
The agent is being rewritten in Go now and is not considered stable, but: in case this is still relevant, the older (Python) implementation was tagged on DockerHub as `getsentry/sentry-kubernetes:py-1.0.0a`.
