### ISSUE TITLE
Cluster cannot be set on Helm chart

### ISSUE THREAD

**Issue by ghost** [getsentry/sentry-kubernetes#36]
Hello,

It appears as though a k8s cluster can be specified via env var `CLUSTER_NAME` (https://github.com/getsentry/sentry-kubernetes/blob/master/sentry-kubernetes.py#L23) but no such option exists in the helm chart: 
https://github.com/helm/charts/blob/master/incubator/sentry-kubernetes/templates/deployment.yaml

Is there a reason `CLUSTER_NAME` was omitted and if not, could it be added to the helm chart?

**Comment by rhcarvalho** [comment]
Hi Jacob! While I'm not familiar with the original work here and thus the omission, I'd suggest the easiest way forward is to fork the chart and customize it to match your particular needs.

The repo https://github.com/helm/charts is being deprecated towards the end of this year.
