### ISSUE TITLE
Pager Duty. not installing

### ISSUE THREAD

**Issue by mpechner-akasa** [getsentry/sentry-kubernetes#57]
### Environment
K8
What version are you running? Etc.
22.11.0
### Steps to Reproduce

Install using https://develop.sentry.dev/integrations/pagerduty/#enable-the-integration-in-sentry
Looking at cron I see the line  in /etc/sentry/config.yaml:
pagerduty.app-id: "PQO???"

I created the app according to the documentation.
I added  pagerduty.app-id to values.yaml:

`config:
  configYml:
    pagerduty.app-id: "PQO???"
`

I applied the change.

pagerduty shows as not installed.

Looking at the logs for the web pod I see:
 00:07:25 [INFO] sentry.access.api: api.access (method='GET' view='sentry.web.frontend.react_page.ReactPageView' response=200 user_id='5' is_app='None' token_type='None' is_frontend_request='True' organization_id='1' auth_id=' │
│ None' path='/settings/sentry/integrations/pagerduty/' caller_ip='10.4.59.25' user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36' rate_limited='Fal │
│ se' rate_limit_category='None' request_duration_seconds=0.12535500526428223 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')                │
│ 00:07:27 [INFO] sentry.access.api: api.access (method='GET' view='sentry.web.frontend.react_page.ReactPageView' response=200 user_id='5' is_app='None' token_type='None' is_frontend_request='True' organization_id='1' auth_id=' │
│ None' path='/settings/sentry/integrations/pagerduty/' caller_ip='10.4.59.25' user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36' rate_limited='Fal │
│ se' rate_limit_category='None' request_duration_seconds=0.0899038314819336 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')

What might I have missed?  What pod should I look at to see errors setting up pagerduty integration?

### Actual Result

What actually happened. Maybe a screenshot/recording? Maybe some logs?

**Comment by tonyo** [comment]
Looks like it was meant for https://github.com/getsentry/sentry/ (the main repository)
If you think it may be specific to the way Sentry self-hosted works, feel free to reopen it there: https://github.com/getsentry/self-hosted
Thanks!
