### ISSUE TITLE
Please provide an oficial docker image

### ISSUE THREAD

**Issue by gianrubio** [getsentry/sentry-kubernetes#6]
I would like to re-package these project in a helm chart, I'm missing an oficial image from sentry. Is it possible to you guys provide this image?

Related to #1

**Comment by bretthoerner** [comment]
When you say official do you just mean under the `sentry` name rather than mine, or what?

**Comment by gianrubio** [comment]
Yes I do! Usually I'd trust more when I saw a docker image from a company rather than from someone that works for that company. I can see that you have one [docker image](https://hub.docker.com/r/bretthoerner/sentry-kubernetes/) on your private account, do you think you can push this image to the sentry account?

**Comment by bretthoerner** [comment]
Done, I updated the readme to point here: https://hub.docker.com/r/getsentry/sentry-kubernetes/

**Comment by gianrubio** [comment]
Thanks @bretthoerner, PR for helm chart is waiting for approval https://github.com/kubernetes/charts/pull/3748
