### ISSUE TITLE
ARM image build

### ISSUE THREAD

**Issue by Goalt** [getsentry/sentry-kubernetes#71]
Hi!
Thank you for your work, project is very helpful for me. 

I'm intersted to use your project on my ARM k8s cluster, but there is no image for such architecture.
I also see there is commented section for such changes:
https://github.com/getsentry/sentry-kubernetes/blob/master/.github/workflows/build-push.yaml#L26C18-L26C18
Is it possible to add them or it was commented for some reason?

**Comment by tonyo** [comment]
When I tried to build ARM images in GitHub Actions last time, it was very slow: the builds were basically timing out, most likely because of a slow QEMU emulation

We would totally welcome a working solution for building ARM images.

**Comment by dotansimha** [comment]
Just noticed the same issue. ARM nodes are not supported :(

**Comment by dotansimha** [comment]
I [forked and ran CI with ARM platform](https://github.com/the-guild-org/sentry-kubernetes/pull/1). If anyone else needs it, you can use the following image: 

```
 ghcr.io/the-guild-org/sentry-kubernetes:d9f489ced1a8eeff4a08c7e2bce427a1545dbbbd
```

**Comment by nohant** [comment]
opened a PR, i hope it could help build time for arm.

**Comment by tonyo** [comment]
Thanks @nohant, this should be fixed by https://github.com/getsentry/sentry-kubernetes/pull/88 now.
